site_name: "CR Explorer"
site_url: https://andreas-thor.github.io/crexplorer_handbook/


nav: 
  - "Home": index.md
  - "Introduction": introduction.md
  - "Run & Download": run_download.md
 


theme: 
  name: material  
#   features:
#     - navigation.tabs
#     - content.tabs.link
#     - navigation.indexes

# markdown_extensions:
#   - admonition
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.tabbed:
#       alternate_style: true
