site_name: Cited References Explorer
nav:
  - "Introduction": index.md
  - "Run & Download": run_download.md
  - "WoS Landmark Papers": https://andreas-thor.github.io/CRExplorer/landmark.html

theme: 
  name: material  
  features:
    - toc.integrate
  logo: CRLogo_white.png
  favicon: favicon.ico
  palette:
      primary: black  

plugins:
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, true]
          concurrency: 8
          # stylesheets:
          #   - resources/stylesheets/pdf.scss
          # covers:
          #   front: resources/templates/covers/front.html.j2
          #   back: resources/templates/covers/back.html.j2
          aggregator:
            enabled: true
            output: site.pdf
            covers: all

      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes        